### PR TITLE
Continue scraping if failures encountered on specific regions

### LINKED ISSUE #297: Failed Scraped Regions prevent other Regions from caching
So locally, `ap-east-1` and `me-south-1` with AWS were causing me issues. For whatever reason, I was getting 401s and 403s, despite having the IAM user configured correctly. This lead to the issue where none of the other regions were getting cached after getting scraped.

### PR DESCRIPTION
**Pull request by mrsheepuk**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #297
| License         | Apache 2.0

### What's in this PR?

Change the error handling while scraping to report the error but continue, failing the overall scrape with the last error encountered.

### Why?

This addresses #297 which I have also run into - it seems that two specific regions (ap-east-1 and me-south-1) both get 401s while all other regions work with an IAM user permissioned as per the guide. This allows cloudinfo to work fully for all other regions rather than scraping nothing for the whole of AWS.

### Additional context

Tested by scraping using valid and invalid credentials - product store is now populated as expected with the exception of the regions having specific failures.

### Checklist
- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)

### CODE REVIEW

**Comment by mrsheepuk** [comment]
@sagikazarmark Any change you could take a look at this one too?

**Comment by sagikazarmark** [comment]
Thanks @mrsheepuk

**Comment by mrsheepuk** [comment]
Thanks both!

**Comment by sagikazarmark** [comment]
@mrsheepuk can you send me your email address: mark[at]banzaicloud.com so that I can contact you outside of GitHub?

**Pull request merged**
